run-dist:
	./build/install/app/bin/app

setup:
	./gradlew wrapper

clean:
	./gradlew clean

run:
	./gradlew run

install:
	./gradlew clean install

build:
	./gradlew clean build --stacktrace

report:
	./gradlew jacocoTestReport

test:
	./gradlew test

checkStyle:
	./gradlew checkstyleMain

.PHONY: build
